name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup package
        uses: ./.github/actions/setup
        with:
          python-version: "3.12"

      - name: Run tests
        run: >
          uv run pytest -v --cov=src -m "not parallelized and not lightning"
          --ignore="benchmark" --ignore="src/meds_torchdata/extensions"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
